CONFIG:=$(addprefix ../,$(CONFIG))
include $(CONFIG)

# CONFIG #
LIBS+=util tty

SERIAL-BAUD:=115200

DEVICE:=STM32F407xx
MATH:=ARM_MATH_CM4
CPU:=cortex-m4
FPU:=fpv4-sp-d16
FLOAT_ABI:=hard
# CONFIG #
