#ifndef _EVALUATION_CONFIG_H_
#define _EVALUATION_CONFIG_H_

#include "stm32f4xx_hal.h"

#include <util.h>
using namespace BITS;

// # INITIALIZATION #
#define INITIALIZATION_VERBOSE
#define INITIALIZATION_FORMAT_OK     Fosl::Tty::DISPLAY_ATTRIBUTE::FG_GREEN
#define INITIALIZATION_FORMAT_FAILED Fosl::Tty::DISPLAY_ATTRIBUTE::FG_RED, Fosl::Tty::DISPLAY_ATTRIBUTE::BOLD
#define INITIALIZATION_MESSAGE_OK     "[+] INITIALIZED DRIVER FOR %s!\n"
#define INITIALIZATION_MESSAGE_FAILED "[-] UNABLE TO INITIALIZE DRIVER FOR %s: %s!\n"

#endif

